version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432

  auth_postgres:
      image: postgres:15
      restart: always
      environment:
        - POSTGRES_HOST=localhost
        - POSTGRES_PORT=5432
        - POSTGRES_USER=$AUTH_POSTGRES_USER
        - POSTGRES_PASSWORD=$AUTH_POSTGRES_PASSWORD
        - POSTGRES_DB=$AUTH_POSTGRES_DB
      ports:
        - 5433:5432

  auth:
    image: rustflix-auth
    depends_on:
      - auth_postgres
    restart: always
    ports:
      - 50051:50051

  graphql-core:
    image: rustflix-graphql-core
    depends_on:
      - postgres
      - auth
    restart: always
    ports:
      - 8080:8080
