version: "3.9"

services:
  auth_mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$AUTH_MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$AUTH_MONGODB_PASSWORD
    ports:
      - 27017:27017

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432

  auth:
    image: movies-api-auth
    depends_on:
      - auth_mongo
    restart: always
    ports:
      - 50051:50051

  graphql-core:
    image: movies-api-graphql-core
    depends_on:
      - postgres
      - auth
    restart: always
    ports:
      - 8080:8080
