CREATE TABLE IF NOT EXISTS users (
  id UUID NOT NULL PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  birthday TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS movies (
    id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(60) NOT NULL UNIQUE,
    description TEXT NOT NULL
);
